name: Release

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - config/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find Latest Tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: misteraddons/Reflex-Adapt
          releases-only: true
        id: latesttag
      - name: Fetch Reflex Updater
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "misteraddons/Reflex-Adapt"
          version: ${{ steps.latesttag.outputs.tag }}
          file: "reflex_updater.sh"
      - name: Generate Repo File
        run: python3 generate_repo.py ${{ steps.latesttag.outputs.tag }}
      - name: Commit Repo File
        uses: EndBug/add-and-commit@v9
        with:
          add: reflexadapt.json.zip